version: '3'
services:
  database:
    container_name: zssn_db
    build:
      context: ./
      dockerfile: mysql
    ports:
      - "3001:3306"
    user: "${UID}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "zssn"
      MYSQL_USER: "zssn_user"
      MYSQL_PASSWORD: "zssn_password"
    networks:
      - spring-network
  php_my_admin:
    container_name: zssn_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_HOST="mysql_app_1"
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=512M
    networks:
      - spring-network
  backend:
    container_name: zssn_backend
    build:
      context: ./
      dockerfile: back
    ports:
      - "8090:8090"
    restart: always
    networks:
      - spring-network
networks:
  spring-network: